In [1]:
import numpy as np

In [2]:
c = np.array([6, 7, 5, 8])
d = np.array([4, 3, 7, 8])
pro = c.dot(d)
print(pro)

144


In [3]:
print(c.transpose())

[6 7 5 8]


In [4]:
print(np.sort(c))

[5 6 7 8]


In [5]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 5, 3, 2]
print(arr[2:-3])

[3, 4, 5, 6, 7, 8]


In [6]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(arr[1::2])

[2, 4, 6, 8, 10]


In [7]:
#stack() is used for joining multiple NumPy arrays
array_1 = np.array([1, 2, 3, 4])
array_2 = np.array([5, 6, 7, 8])
array_new = np.stack((array_1, array_2), axis = 1)
print(array_new)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [8]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b.T), axis = 1))

[[1 2 5]
 [3 4 6]]


In [9]:
array_1 =np.array([[1, 2, 3, 4, 5], [20, 30, 40, 50, 60]])
array_2 = np.array([[6, 7, 8, 9, 10], [9, 8, 7, 6, 5]])
array_1 =np.column_stack([array_1, array_2])

In [10]:
array_1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [20, 30, 40, 50, 60,  9,  8,  7,  6,  5]])

In [27]:
array = [1, 3, 16, 2, 4, 38, 9, 10, 12, 7]
print(array % 3)

TypeError: unsupported operand type(s) for %: 'list' and 'int'